# ==========================================
# 1. CẤU HÌNH ICEBERG CATALOG (JDBC)
# ==========================================
spark.sql.extensions                               org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions
spark.sql.catalog.lakehouse                        org.apache.iceberg.spark.SparkCatalog
spark.sql.catalog.lakehouse.type                   jdbc
spark.sql.catalog.lakehouse.uri                    jdbc:postgresql://postgres-catalog:5432/iceberg_metadata?user=admin&password=password
spark.sql.catalog.lakehouse.warehouse              s3a://warehouse/
spark.sql.catalog.lakehouse.jdbc.user              admin
spark.sql.catalog.lakehouse.jdbc.password          password
spark.sql.catalog.lakehouse.jdbc.schema-version    V1
spark.sql.defaultCatalog                           lakehouse

# ==========================================
# 2. CẤU HÌNH MINIO (S3 STORAGE BACKEND)
# ==========================================
spark.hadoop.fs.s3a.endpoint                       http://minio:9000
spark.hadoop.fs.s3a.access.key                     admin
spark.hadoop.fs.s3a.secret.key                     password
spark.hadoop.fs.s3a.path.style.access              true
spark.hadoop.fs.s3a.impl                           org.apache.hadoop.fs.s3a.S3AFileSystem
spark.hadoop.fs.s3a.connection.ssl.enabled         false

# ==========================================
# 3. CẤU HÌNH HIVE METASTORE CHO THRIFT SERVER (POSTGRES)
# ==========================================
'''spark.hadoop.javax.jdo.option.ConnectionURL        jdbc:postgresql://postgres-catalog:5432/iceberg_metadata
spark.hadoop.javax.jdo.option.ConnectionDriverName org.postgresql.Driver
spark.hadoop.javax.jdo.option.ConnectionUserName   admin
spark.hadoop.javax.jdo.option.ConnectionPassword   password'''

# ==========================================
# 4. FIX LỖI DERBY (ÉP TỰ ĐỘNG TẠO BẢNG HIVE VÀO POSTGRES)
# ==========================================
'''spark.hadoop.datanucleus.schema.autoCreateAll                  true
spark.hadoop.datanucleus.schema.autoCreateTables               true
spark.hadoop.datanucleus.schema.autoCreateColumns              true
spark.hadoop.datanucleus.autoCreateSchema                      true
spark.hadoop.datanucleus.autoCreateTables                      true
spark.hadoop.datanucleus.autoCreateColumns                     true
spark.hadoop.datanucleus.fixedDatastore                        false
spark.hadoop.hive.metastore.schema.verification                false
spark.hadoop.hive.metastore.schema.verification.record.version false'''
